const ActionTypes = {

// ================Product============//

   REQ_GET_REGION: 'REQ_GET_REGION',
   UPDATE_REGION: 'UPDATE_REGION',
   UPDATE_REGION_RESPONSE: 'UPDATE_REGION_RESPONSE',
   GET_REGION: 'GET_REGION',
   GET_REGION_RESPONSE: 'GET_REGION_RESPONSE',
   ADD_REGION: 'ADD_REGION',
   ADD_REGION_RESPONSE: 'ADD_REGION_RESPONSE',
   DEL_REGION: 'DEL_REGION', 
   DEL_REGION_RESPONSE: 'DEL_REGION_RESPONSE',

};
export default ActionTypes