const actionTypes = {
  //* RESTO_MENUS
  GET_REME_RESPONSE: 'GET_REME_RESPONSE',
  REQ_GET_REME: 'REQ_GET_REME',
  ADD_REME: 'ADD_REME',
  ADD_REME_RESPONSE: 'ADD_REME_RESPONSE',
  UPDATE_REME: 'UPDATE_REME',
  UPDATE_REME_RESPONSE: 'UPDATE_REME_RESPONSE',
  DEL_REME: 'DEL_REME',
  DEL_REME_RESPONSE: 'DEL_REME_RESPONSE',
  SEARCH_REME: 'SEARCH_REME',
  SEARCH_REME_RESPONSE: 'SEARCH_VENDOR_RESPONSE',

  //* RESTO_MENU_PHOTOS
  GET_REPHO_RESPONSE: 'GET_REPHO_RESPONSE',
  REQ_GET_REPHO: 'REQ_GET_REPHO',
  ADD_REPHO: 'ADD_REPHO',
  ADD_REPHO_RESPONSE: 'ADD_REPHO_RESPONSE',
  UPDATE_REPHO: 'UPDATE_REPHO',
  UPDATE_REPHO_RESPONSE: 'UPDATE_REPHO_RESPONSE',
  DEL_REPHO: 'DEL_REPHO',
  DEL_REPHO_RESPONSE: 'DEL_REPHO_RESPONSE',
}

export default actionTypes
